
services:
  # 웹 서버 설정
  web:
    build: ./web              # 웹 서버 코드로 이미지 만들기
    ports:
      - "8000:8000"          # 8000번 포트로 접속 가능
    volumes:
      - ./code:/app          # 코드 수정이 바로 반영되도록
    environment:
      - DEBUG=true           # 개발 모드 활성화
    depends_on:
      - db                   # 데이터베이스 먼저 실행

  # 데이터베이스 설정
  db:
    image: mysql:8.0         # MySQL 데이터베이스 사용
    volumes:
      - db_data:/var/lib/mysql  # 데이터 저장
    environment:
      - MYSQL_ROOT_PASSWORD=secret  # 데이터베이스 비밀번호

volumes:
  db_data:  # 데이터베이스 저장소


# docker compose up -d 도커 컴포즈 실행
